# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='create_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='modified_at',
            field=models.DateField(auto_created=True),
        ),
    ]
