# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20160906_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='modified_at',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
